---
kind: pipeline
type: docker
name: build

steps:
  - name: docker image
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      registry: docker.io
      repo: src386/kotorbuilds
      tags: latest

node:
  role: builder

---
kind: pipeline
type: docker
name: deploy
depends_on: 
  - build
clone:
  disable: true

steps:
  - name: local webserver
    image: src386/kotorbuilds:latest
    commands:
      - "apk --no-cache add rsync"
      - "rsync -av --delete /usr/share/nginx/html/* /mnt/kotorbuilds/"
    volumes:
      - name: kotorbuilds
        path: /mnt/kotorbuilds

node:
  role: webserver

volumes:
  - name: kotorbuilds
    host:
      path: /var/www/html/kotorbuilds.src386.org
