---
kind: pipeline
type: docker
name: Docker images

steps:
  - name: Build and Push
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      registry: docker.io
      repo: src386/kotorbuilds
      tags: 
        - latest

trigger:
  branch:
  - master

node:
  role: builder

---
kind: pipeline
type: docker
name: Remote deploy

steps:
  - name: build
    image: ghcr.io/getzola/zola:v0.15.3
    command:
      - build

  - name: rsync
    image: alpine:latest
    commands:
      - apk add --no-cache openssh-client rsync
      - eval $(ssh-agent -s)
      - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      - >
        rsync
        --recursive
        --verbose
        --checksum
        --delete
        --chown=wwwrun:www-data
        --chmod=770
        $DRONE_WORKSPACE/public/*
        $USER@$HOST:/var/www/html/kotorbuilds.src386.org/
    environment:
      KNOWN_HOSTS:
        from_secret: ssh_fingerprint
      HOST: kotorbuilds.src386.org
      USER:
        from_secret: ssh_user
      PRIVATE_KEY:
        from_secret: ssh_private_key

node:
  role: builder

trigger:
  branch:
  - master
