name: Docker Image

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - .gitignore
      - .gitattributes

jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: src386/kotorbuilds:latest
          platforms: linux/amd64
